version: '3.8'

services:
  ml-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ml-data:/app/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  ml-data: 